/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Options for the Markdown compiler. */
export interface CompileOptions {
  /** Enables tables (GFM). */
  tables?: boolean
  /** Enables footnotes. */
  footnotes?: boolean
  /** Enables strikethrough (GFM). */
  strikethrough?: boolean
  /** Enables task lists (GFM). */
  tasklists?: boolean
  /** Enables smart punctuation (e.g. smart quotes, dashes). */
  smartPunctuation?: boolean
  /** Enables heading attributes (e.g. {#id}). */
  headingAttributes?: boolean
  /** Enables metadata blocks (YAML and Plus-style frontmatter). */
  metadataBlocks?: boolean
  /** Enables LaTeX math blocks. */
  math?: boolean
  /** Enables all GFM extensions. */
  gfm?: boolean
}

/**
 * Extracts metadata (frontmatter) from the beginning of the Markdown document.
 *
 * Returns the raw content of the YAML or Plus-style metadata block.
 */
export declare function extractMetadata(markdownInput: string): string | null

/**
 * Parses the Markdown document and returns a list of headings.
 *
 * Useful for building a Table of Contents (TOC).
 */
export declare function getHeadings(markdownInput: string): Array<Heading>

/** Represents a heading in the document. */
export interface Heading {
  /** Level of the heading (1 to 6). */
  level: number
  /** Text content of the heading. */
  text: string
  /** Optional ID attribute (e.g. from `{#id}`). */
  id?: string
}

/**
 * Converts a Markdown string to HTML.
 *
 * # Arguments
 * * `markdown_input` - The Markdown source string.
 * * `options` - Optional compiler configuration.
 */
export declare function markdownToHtml(markdownInput: string, options?: CompileOptions | undefined | null): string

/**
 * Converts Markdown to plain text by stripping all formatting.
 *
 * Excludes metadata blocks and ensures proper spacing between block elements.
 */
export declare function markdownToPlainText(markdownInput: string): string
